### ISSUE TITLE
Bad link to Pd examples

### ISSUE THREAD

**Issue by joebowbeer** [clevelandmusicco/HothouseExamples#12]
The link to Pd examples in the wiki section [Pure Data (Pd) examples](https://github.com/clevelandmusicco/HothouseExamples/wiki/Hothouse-Examples#pure-data-pd-examples) is wrong.

It should link to:

https://github.com/clevelandmusicco/HothouseExamples/blob/main/pd/README.md

**Comment by clevelandmusicco** [comment]
Right you are. Cheers for that. All fixed!
